#########################
# Definicion de las POD
#########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - name: customers
        image: acrjoyapu.azurecr.io/customers
        #args:
        #- -listen=:8080
        #- '-text=Hi from #ytt apple'
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred
---
#########################
# Definicion del servicio
#########################
kind: Service
apiVersion: v1
metadata:
  name: customers
spec:
  selector:
    app: customers
  ports:
  - port: 80
    targetPort: 9001


